executable            = trkeff_varZref.sh

output                = output/trkeff_varZref_$(ProcId).out
error                 = error/trkeff_varZref_$(ProcId).err
log                   = log/trkeff_varZref_$(ProcId).log

getenv                = False
notification          = Never
requirements          = (OpSysAndVer =?= "AlmaLinux9")
should_transfer_files = IF_NEEDED

+JobFlavour           = "workday"
+AccountingGroup      = "group_u_SNDLHC.users"

queue arguments from args_varZref.txt
